### ISSUE TITLE
Add action to the button (Go to second Mainpage)

### ISSUE THREAD

**Issue by Lourievc** [toledobh/news-scraping#12]
"Play" button in main page

**Comment by Lourievc** [comment]
Story points: 1

**Comment by yguzman2022** [comment]
I didn't get to finish this task. I accidentally broke the code that had the widget with the button. Even though I got to fix the errors, I still have some other errors that show after I add the widget and build an ElevatedButton.

The error I'm getting appears after adding the Navigator.push() method.

**Comment by toledobh** [comment]
The play button in the page called "instructions" needs to go to the main page.
