### ISSUE TITLE
Create game page to add slide feature

### ISSUE THREAD

**Issue by Lourievc** [toledobh/news-scraping#14]
Slide for true and false in the game

**Comment by Lourievc** [comment]
Story points: 5

**Comment by MiriamJB** [comment]
YouTube tutorial that I've been using:
https://www.youtube.com/watch?v=bFbR5p1a8WA&list=PLCAZyR6zw2pyyjdifS_AFJf6HA4Ud8R4_&index=2
Episodes 1 & 2

**Comment by MiriamJB** [comment]
**Done:**
* create another page to host the main page
* create framework for news card
* add buttons to display which way to pull for true/false

**To-Do:**
* add swipe function to the card
* reveal another card under the swiped card
* add functionality to the true/false buttons (if needed)
